# fly.toml app configuration file for GoatCounter
app = "goatcounter"
primary_region = "sin"

[build]

[http_service]
internal_port = 8080
force_https = true
auto_stop_machines = "stop"
auto_start_machines = true
min_machines_running = 0
processes = ["app"]

# 🧱 Mount persistent volume for SQLite DB
[[mounts]]
source = "data"
destination = "/app/db"

# 🩺 Optional: simple health check (helps Fly restart cleanly if needed)
[[checks]]
type = "http"
name = "status"
interval = "10s"
timeout = "2s"
grace_period = "10s"
path = "/"
port = 8080

[[vm]]
memory = "1gb"
cpu_kind = "shared"
cpus = 1
